FROM php:8.2-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql

COPY services/frontend/app/ /var/www/html/

RUN sed -i 's/80/10000/g' /etc/apache2/ports.conf /etc/apache2/sites-available/000-default.conf

EXPOSE 10000
